import { BandsEntity } from './bands.entity';
import { BatteryLifeEntity } from './batterylife.entity';
import { BloodSampleDetailEntity } from './bloodsampledetail.entity';
import { CaptureDetailEntity } from './capturedetail.entity';
import { CheckmateEntity } from './checkmate.entity';
import { ChickHealthEntity } from './chickhealth.entity';
import { ChipsEntity } from './chips.entity';
import { EggHealthEntity } from './egghealth.entity';
import { EggTimerEntity } from './eggtimer.entity';
import { HandRaiseEntity } from './handraise.entity';
import { HarnessChangeEntity } from './harnesschange.entity';
import { HealthCheckEntity } from './healthcheck.entity';
import { HealthStatusEntity } from './healthstatus.entity';
import { LocationBearingEntity } from './locationbearing.entity';
import { MeasureDetailEntity } from './measuredetail.entity';
import { MedicationEntity } from './medication.entity';
import { ObserverEntity } from './observer.entity';
import { OtherSampleEntity } from './othersample.entity';
import { SnarkDataEntity } from './snarkdata.entity';
import { SpermSampleEntity } from './spermsample.entity';
import { StandardEntity } from './standard.entity';
import { SupplementaryFeedingEntity } from './supplementaryfeeding.entity';
import { SwabSampleEntity } from './swabsample.entity';
import { TransferDetailEntity } from './transferdetail.entity';
import { TransmitterChangeEntity } from './transmitterchange.entity';
import { TxActivityEntity } from './txactivity.entity';
import { WeightEntity } from './weight.entity';
import { BaseEntity } from './base-entity';

export class RecordEntity extends BaseEntity {
  activity: string;
  birdCert: string;
  birdID: string;
  booming: number;
  comments: string;
  dateTime: Date;
  duration: number;
  easting: number;
  entryDateTime: Date;
  errol: boolean;
  firstArriveTime: Date;
  island: string;
  lastDepartTime: Date;
  locationID: string;
  mappingMethod: string;
  nesting: number;
  northing: number;
  numberOfVisits: number;
  obsQuality: string;
  oldBirdID: string;
  oldBoomingIntensity: number;
  oldHealthStatus: string;
  oldLocationDescription: string;
  oldLocationName: string;
  oldObserver: string;
  reason: string;
  recordID: string;
  recordType: string;
  signalRcvdLocation: string;
  significantEvent: boolean;
  subReason: string;
  supFed: number;
  transmitterId: string;
  bands: BandsEntity;
  batteryLife: BatteryLifeEntity;
  bloodSampleDetail: BloodSampleDetailEntity;
  captureDetail: CaptureDetailEntity;
  checkmate: CheckmateEntity;
  chickHealth: ChickHealthEntity;
  chips: ChipsEntity;
  eggHealth: EggHealthEntity;
  eggTimer: EggTimerEntity;
  handRaise: HandRaiseEntity;
  harnessChange: HarnessChangeEntity;
  healthCheck: HealthCheckEntity;
  healthStatus: HealthStatusEntity;
  locationBearingList: LocationBearingEntity[];
  measureDetail: MeasureDetailEntity;
  medicationList: MedicationEntity[];
  observerList: ObserverEntity[];
  otherSampleList: OtherSampleEntity[];
  snarkData: SnarkDataEntity;
  spermSampleList: SpermSampleEntity[];
  standard: StandardEntity;
  supplementaryFeeding: SupplementaryFeedingEntity;
  swabSampleList: SwabSampleEntity[];
  transferDetail: TransferDetailEntity;
  transmitterChange: TransmitterChangeEntity;
  txActivity: TxActivityEntity;
  weight: WeightEntity;
  magneticDeclination: number;
  magneticDeclinationAsOfYear: number;

  constructor() {
    super();
    this.docType = 'Record';
  }
}
